### ISSUE TITLE
SWI port of CLP(Q) has elementary mistakes

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-clpqr#4]
See for example a [recent report](http://eu.swi-prolog.org/forum?place=msg%2Fswi-prolog%2FM1nCtEbOcis%2F8sxlD1NrAAAJ):

<pre>
?- {1 =< Z, Z =< 5, 1 =< X, X =< 5, Z+1 =< X}, bb_inf([Z,X],-Z,Min,_V2).
<b>Min = -3,</b>
_V2 = [3, 5],
{X=<5, <b>_2002</b>=1+Z-X, Z-X=< -1, Z>=1}.
</pre>

Comparing with CLP(FD):

<pre>
?- [X,Z] ins 1..5, Z+1 #=< X, labeling([min(-Z)], [Z,X]).
X = 5,
<b>Z = 4 .</b>
</pre>

This shows that the minimum is **-4**, not **-3**.

In addition, the internal variable `_2002` should **not occur** in the answer. See #3.

Everything works exactly as expected in SICStus Prolog:

<pre>
| ?- {1 =< Z, Z =< 5, 1 =< X, X =< 5, Z+1 =< X}, bb_inf([Z,X],-Z,Min).
<b>Min =  -4,</b>
{X=<5},
{Z-X=< -1},
{Z>=1} ? ;
no
</pre>

Note that:

- the result is **correct** (`-4`)
-  all variables that occur in residual goals also occur in the&nbsp;query.

I'm filing this as one of the issues I need to fix either in CLP(Q) or its reimplementation.

See the [**roadmap item**](https://github.com/SWI-Prolog/roadmap/issues/27).

**Comment by JanWielemaker** [comment]
I had a look, in part to understand more about the status of this library and in part because earlier issues were causes by SWI-Prolog rational number arithmetic issues and of course because wrong answers are the most serious class of issues.

Pushed some cleanup to make the code more accessible.   It takes more time to find the issue.  I did make these observations:

     ?- {1 =< Z, 1 =< X, X =< 5, Z+1 =< X},  bb_inf([Z,X],-Z,Min,_V2).
     Min = -4

However, any upper bound placed on `Z` that should not affect the result cause the result to be `-3`.  Adding e.g., `Z =< 2` produces the right (`-2`) result.

All in all, the code itself seems clean enough to maintain.  The lack of tests, notably for the various components, make it hard to isolate bugs.  Just going through this simple example shows so many intermediate results where you wonder whether they are right or wrong that it is hard to isolate the bug.

**Comment by andreaf96** [comment]
@triska @JanWielemaker This bug is solved in this https://github.com/SWI-Prolog/packages-clpqr/pull/6 pull request. Please review and accept it.

**Comment by andreaf96** [comment]
The patch has been applied and the bug is fixed.

**Comment by triska** [comment]
@andreaf96: Thank you a lot, I am closing this issue!
